# <span style="color:darkblue"> Lecture 3: Mathematical Operations and Random Numbers </span>

<font size="5"> 

In the previous class we:
- Introduced lists and variable types
- Talked about how to extract elements from a list

<font size="5"> 

In this class we will:

- Introduce a library for general mathematical operations
- Generate random numbers
- (Optional) Matrix operations

## <span style="color:darkblue"> I. Import Libraries </span>

In [1]:
# the "numPy" library is used for mathematical operations
# the "matplotlib" library is for generating graphs

import numpy as np
import matplotlib.pyplot as plt


##  <span style="color:darkblue"> II. Numbers and Functions </span>

<font size = "5" >
Examples of numPy numbers

In [2]:
# Computes "pi" (3.14...)

np.pi

3.141592653589793

<font size = "5" >

Examples of numPy functions

$ ln(x), e^x, sin(x), cos(x), \sqrt{x}$

In [3]:
# log(x) computes the logarithm with base "e" (Euler constant)
# exp(x) compute the Euler constant raised to the power of "x"
# sing(x) computes the sine of x
# cos(x) computes the cosine of x
# In this example, we're substituting x = 1

print(np.log(1))
print(np.exp(1))
print(np.sin(1))
print(np.cos(1))
print(np.sqrt(1))

0.0
2.718281828459045
0.8414709848078965
0.5403023058681398
1.0


<font size = "5">

Raising to the power of a number

$ x^5 $

In [6]:
x = 10
x ** 5

# Not x^5

100000

<font size = "5">

Try it yourself!

- Create a new variable, $x = 5$
- Compute $\pi x^2$
- Compute $ \frac{1}{\sqrt{2\pi}}e^{-x^2} $

In [4]:
# Write your own code

x = 5
print(np.pi*(x**2))
print(1/(np.sqrt(2*np.pi))*np.exp(-x**2))


78.53981633974483
5.540487995575833e-12


##  <span style="color:darkblue"> III. Vector Arrays </span>

<font size = "5">
Create an array from a list

$ \text{ }$
$ a = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}
\qquad b = \begin{pmatrix} 0 \\ 1 \\ 0\end{pmatrix}
\qquad c = \begin{pmatrix} 10 \\ 100 \\ 1000 \\ 2000 \\ 5000 \end{pmatrix} 
\qquad d = \begin{pmatrix} 4 \\ 2 \end{pmatrix} $

In [6]:
# You create an array by converting a list [1,2,3] to a numeric object
# "array" is a subfunction of the library numPy.

vec_a  = np.array([1,2,3])
vec_b  = np.array([0,1,0])
vec_c  = np.array([10,100,1000,2000,5000 ])


<font size = "5">

Accessing an element of an array

In [7]:
# Arrays, like lists, start their numbering at zero.
# You also access them with square brackets

print(vec_a[0])
print(vec_a[2])


1
3


<font size = "5">
Operations with a single array and a scalar

<font size = "5">

$ a + 2 = \begin{pmatrix} a_1 + 2 \\ a_2 + 2 \\ a_3 + 2 \end{pmatrix}$

In [8]:
# A scalar refers to either an int or float
# We can do many common operations with 

print(vec_a * 2)
print(vec_a / 2)
print(vec_a + 2)
print(vec_a ** 2)

[2 4 6]
[0.5 1.  1.5]
[3 4 5]
[1 4 9]


<font size = "5">
Element-by-element addition between two arrays of the same size

$\text{ }$

$ a + b = \begin{pmatrix} a_1 \\ a_2 \\ a_3 \end{pmatrix} +
          \begin{pmatrix} b_1 \\ b_2 \\ b_3 \end{pmatrix} =
          \begin{pmatrix} a_1 + b_1 \\ a_2 + b_2 \\ a_3 + b_3 \end{pmatrix}$

In [9]:
print(vec_a)
print(vec_b)

[1 2 3]
[0 1 0]


In [10]:
# When you add two arrays of the same size,
# Python adds the individual elements in each position

print(vec_a + vec_b)


[1 3 3]


<font size ="5">

The default multiplication option is element-by element:

$ a * b = \begin{pmatrix} a_1 * b_1 \\ a_2 * b_2 \\ a_3 * b_3 \end{pmatrix}$

In [11]:
# We can do other similar element-by-element operations
# such as multiplication, subtraction, and division.

print(vec_a * vec_b)
print(vec_a - vec_b)
print(vec_a / vec_b)


[0 2 0]
[1 1 3]
[inf  2. inf]


/var/folders/m3/6j81lywj4tngb6ydznwtqvs00000gp/T/ipykernel_37616/3839639845.py:6: RuntimeWarning: divide by zero encountered in divide
  print(vec_a / vec_b)


<font size = "5">
Summary statistics of an array

In [12]:
# The function np.mean() computes the mean of an array
# We can do similar operations for the standard deviation (std),
# the minimum (min), the median (median), and the maximum (max).

print(np.mean(vec_a))
print(np.std(vec_a))
print(np.min(vec_a))
print(np.median(vec_a))
print(np.max(vec_a))

2.0
0.816496580927726
1
2.0
3


<font size = "5">

Try it yourself! Compute the mean of


$ e = \begin{pmatrix} 10 \\ 8 \\ 15 \\ 0 \\ 24 \end{pmatrix} $

In [13]:
# Create your own array and compute any of the above summary statistics

e = np.array( [10,8,15,0,24] )

np.mean(e)




11.4

<font size = "5">
<span style="color:red"> Common Pitfall </span>: Make sure that the arrays have the same size

In [14]:
print(vec_a)
print(vec_c)

[1 2 3]
[  10  100 1000 2000 5000]


In [17]:
vec_a.shape

(3,)

In [18]:
# Here I try to combine two arrays of different size.

vec_a + vec_c

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

##  <span style="color:darkblue"> IV. Random Numbers </span>

<font size = "5">

Why randomness?

- Simulate different scenarios: high risk or low risk
- Study properties of a complex system and/or estimator
- In medicine, randomly assign subjects to treatment or control

<font size = "5">

Create a vector of random variables

In [19]:
# This code creates a vector of random variables 
# generated from a normal distribution with
# mean "loc" (location) and standard deviation "scale"
# the number of distinct variabels is "size"

randomvar_a = np.random.normal(loc=0, scale=1, size=10)
print(randomvar_a)

[ 2.55135059 -0.63350366 -0.32665974  1.37555459  1.43701557  0.81032904
 -1.59630941 -0.68685705 -0.00898255 -0.27063612]


<font size = "5">

Random numbers differ every time!

- Avoid this problem by drawing from a "pregenerated" set.
- This is called a seed

<font size = "5">
Transpose

$ \text{ }$

$ Y' = \begin{pmatrix}  1 & 0 & 1 \\ 2 & 1 & 0  \end{pmatrix} $

In [ ]:
# Matrix Transpose
np.matrix.transpose(Y)

<font size = "5">

Matrix multiplication

$ XY = \begin{pmatrix} 1 & 2 & 3 \\ 
                       0 & 4 & 5 \\
                       0 & 0 & 6
                       \end{pmatrix}
                       \begin{pmatrix} 1 & 2 \\ 0 & 1 \\ 1 & 0 \end{pmatrix} = 
        \begin{pmatrix} 4 & 4 \\ 5 & 4 \\ 6 & 0 \end{pmatrix} $

In [ ]:
# Matrix Multiplication

np.dot(X,Y)

np.matmul(X,Y)

<font size = "5">

Matrix inverse

$ X^{-1} = \begin{pmatrix} 1 & 2 & 3 \\ 
                       0 & 4 & 5 \\
                       0 & 0 & 6
                       \end{pmatrix}^{-1} $

In [ ]:
# Check the determinant of a matrix (a matrix is invertible if the determinant is not zero)
print(np.linalg.det(X))

# Matrix inverse
# The following command stands for linear algebrar inverse.
X_inv = np.linalg.inv(X)

# Output the result
print(X_inv)


<font size = "5">

Try it yourself! Check that this is indeed an inverse:

$X X_{inv} = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}$

In [ ]:
# Multiply "X" times "X_inv" using the command shown above
# Note: Sometimes the result is shown in scientific notation.



